development:
  dialect: postgres
  database: stateful_app_development
  user: postgres
  password: iQ36dUHlxF
  host: statefulapp-db-postgresql
  pool: 5

test:
  dialect: postgres
  database: stateful_app_development
  user: postgres
  password: iQ36dUHlxF
  host: statefulapp-db-postgresql
  pool: 5
  #url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@statefulapp-db-postgresql:5432/stateful_app_test?sslmode=disable"}}

production:
  dialect: postgres
  database: stateful_app_development
  user: postgres
  password: iQ36dUHlxF
  host: statefulapp-db-postgresql
  pool: 5
 # url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@statefulapp-db-postgresql:5432/stateful_app_production?sslmode=disable"}}